# Generated by Django 4.2.30 on 2026-05-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityrecord',
            name='co2e_factor',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='co2e_factor_source',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='co2e_factor_unit',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='co2e_kg',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
    ]
